# Generated by Django 5.1.4 on 2025-01-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=200)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_creation_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('deposit_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_creation_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='myapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawTransaction',
            fields=[
                ('withdraw_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('withdraw_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withdraw_creation_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='myapp.account')),
            ],
        ),
    ]
